#!/usr/bin/env node

const Path = require('path');
const fs = require('fs');

const topDir = Path.resolve(Path.join(__dirname, '..'));

try {
  const yaa = fs.readFileSync(Path.join(topDir, "yaa-browser-template.js"), 'utf-8');
  const context = `(()=>{
${fs.readFileSync(Path.join(topDir, "lib", "context.js"))}})();`;
  const module = `(()=>{
${fs.readFileSync(Path.join(topDir, "lib", "module.js"))}})();`;

  fs.writeFileSync(Path.join(topDir, 'yaa.js'), yaa.replace(
      /___INSERT___/, `
const module = {};
${context}
const Context = module.exports;
${module}
const Module = module.exports;
`));
} catch(ex) {
  process.stderr.write(ex.stack);
  process.exit(1);
}
